server:
  port: 9005
spring:
  application:
    name: zyg-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.12:3306/zyg_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    name: root
    password: 123
  thymeleaf:
    cache: false
logging:
  level:
    com.zyg.user: debug
